# Docker Compose configuration for ChemWise
version: '3.8'

services:
  chemwise:
    build:
      context: .
      dockerfile: Dockerfile
    image: chemwise:latest
    container_name: chemwise-app
    restart: unless-stopped
    
    # Environment variables
    environment:
      - PYTHONUNBUFFERED=1
      - CHEMWISE_DATA_DIR=/app/data
      - CHEMWISE_OUTPUT_DIR=/app/output
    
    # Volume mounts for persistent data and easy file access
    volumes:
      - ./data:/app/data:rw
      - ./output:/app/output:rw
      - ./examples:/app/examples:ro
    
    # Working directory
    working_dir: /app
    
    # Keep container running for interactive use
    tty: true
    stdin_open: true
    
    # Resource limits (adjust based on your needs)
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          cpus: '1.0'
          memory: 2G
    
    # Network configuration
    networks:
      - chemwise-net

  # Optional: Jupyter notebook service for interactive computing
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    image: chemwise-jupyter:latest
    container_name: chemwise-jupyter
    restart: unless-stopped
    
    ports:
      - "8888:8888"
    
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=chemwise-token
    
    volumes:
      - ./data:/app/data:rw
      - ./output:/app/output:rw
      - ./examples:/app/examples:ro
      - ./notebooks:/app/notebooks:rw
    
    working_dir: /app
    
    networks:
      - chemwise-net
    
    depends_on:
      - chemwise

networks:
  chemwise-net:
    driver: bridge

volumes:
  chemwise-data:
    driver: local
  chemwise-output:
    driver: local
